### ISSUE TITLE
Putting sourceAnchor on associations should not be generic, but per MM

### ISSUE THREAD

**Issue by badetitou** [moosetechnology/Famix#136]
Currently, ALL TAssociations have a source anchor.
However, it can make no sense for some metamodel.
We should add this information lower in the hierarchy, for example, only for the FamixJava and Smalltalk metamodel
Thus, it will reduce the size of the models

(and add tests :) )

**Comment by anneetien** [comment]
There is no FamixJavaAssociation.
So do we want to put it on FamixTInvocation, FamixTInheritance, FamixTAccess and FamixTReference and remove it from FamixTAssociation?
@badetitou @NicolasAnquetil

**Comment by NicolasAnquetil** [comment]
Does not seem to make much sense to put it on the 4  FamixTInvocation, FamixTInheritance, ... instead of their super-trait
 if we remove it, then remove it for good and add it only in the language MM
(and this is easy, just use TSourceEntity)

But I would also like to be remembered the initial reason why we might not want sourceAnchors in association ...
@badetitou do you remember why the issue was created ?

**Comment by badetitou** [comment]
I think we can close this exception. I have no use case for now. And nobody remembers the deep reason.

I suppose it was if someone want to define a new kind of association, but do not need the source anchor.
For example: an association to represent the link between two widgets in the Casino project ?
