### ISSUE TITLE
TSourcedEntity should not use TWithSourceLanguage by default

### ISSUE THREAD

**Issue by ClotildeToullec** [moosetechnology/Famix#177]
See #58

**Comment by NicolasAnquetil** [comment]
OK, we failed to make the tests pass because the model re-generation behaved strangely.
Once #declaredSourceLanguage is removed from TSourceEntity, one must :
- change FamixTest1Generator so that entities use TWithSourceLanguage (because various tests depend on that)
- change FAMIXCompatibilityGenerator so that #sourceEntity also use TWithSourceLanguage (because the compatibility metamodel must have it, and several tests depend on it)
