### ISSUE TITLE
Compatibility: about modifiers

### ISSUE THREAD

**Issue by ClotildeToullec** [moosetechnology/Famix#209]
Follow-up from discussion in https://github.com/moosetechnology/Famix/pull/206#pullrequestreview-566942952.

After the removal of THasModifiers, the ```modifiers``` accessor is missing and the loading of previously generated models fails.

A fast solution would be to keep a deprecated THasModifiers with only ```modifiers``` accessors and make new traits use it (TCanBeAbstract, TCanBeFinal and THasVisibility). If the property is derived, newly created models will not need the deprecated trait in the future.

Problem: keeping THasModifiers a bit longer for compatibility reasons
Advantage: easy to remove later.

@anneetien @badetitou @NicolasAnquetil I would like your opinion on the subject.

**Comment by badetitou** [comment]
Loading previously generated models put the modifiers in the cache by default.
This is not a problem, but we can create a method `modifiers` that do the "look in the cache if modifiers are present and return it or an empty collection"

Keeping a Deprecated trait for compatibility reason is not a problem for me.
Especially since VerveineJ is not updated yet.

**Comment by anneetien** [comment]
I don't think this issue is still relevant. I close it.
