### ISSUE TITLE
Make #allClients more explicit

### ISSUE THREAD

**Issue by ClotildeToullec** [moosetechnology/Famix#439]
#allClients  actually returns all clients at the scope of the entity. It is not always the expected behavior.
We should have an explicit method for that (something meaning"#allClientsAtMyScope") and #allClients should return the actual client entities.

**Comment by jecisc** [comment]
It was the goal of allClients to get back at the scope. To get all dependencies without scoping there is #queryAllIncoming IIRC. 
the term “client” was used to say “incoming dependencies of my scope” and “provider” to say “outgoing dependencies of my scope”

**Comment by anneetien** [comment]
It is not because the purpose at the beginning to consider the term “client” as “incoming dependencies of my scope” and “provider” to say “outgoing dependencies of my scope” that it is good.
So according to me, the issue has to be performed anyway, otherwise we can't do allClients with the queryBrowser.

**Comment by anneetien** [comment]
Fix with #649
