### ISSUE TITLE
Error in the Pharo Importer

### ISSUE THREAD

**Issue by anneetien** [moosetechnology/Famix#552]
- Open the Moose Model
- Create a Pharo Model (for example take the 9 AI packages).
- In the resulting model, you have 154 classes (stub and not)
- If you select the stub classes, the beginning of the list is 
<img width="181" alt="image" src="https://user-images.githubusercontent.com/17824579/220583615-7b51ce8d-f7bc-442b-8a13-ef4a6b2dc6de.png">
- If you go in allPackages > Collections-Sequenceable and then childEntities, you have the following result
<img width="232" alt="image" src="https://user-images.githubusercontent.com/17824579/220584335-560be93c-5db6-4060-94fb-aa6f604c3c49.png">
As you can see in this second list, _Array2D_ appears whereas it was not in the first list.
While exporting the model _Array2D_ is not exported.

The bug comes perhaps from MooseImportClassesTask.

**Comment by ClotildeToullec** [comment]
The problem comes from this: 
- The lists of candidates are the last thing computed when creating a model.
- For each candidates list, if the method does not exist, it is created as stub, its class is created in the importer *as a normal class*
- This class is never added to the model.

It is easy to add these stub classes in the model. 
⚠️ Please note: this creates a lot of classes (1490 classes for a model with only the first AI package).

However, in the importer, stub classes are created in the same way as model classes. Thus, they have a parentPackage, attributes, comments, source text, inheritance, ...
If these elements are not already in the model, we are only moving the problem and get packages, attributes, ... that are accessible from classes but are not in the model and do not know it.

Proposed solution: create stub classes with less information than model classes: only know the stub methods needed.
Maybe they could know their parent package, that would have to also be created as stub and added to the model.

Again, this adds a lot of stub entities in the model. But actually they were already silently there.

**Comment by ClotildeToullec** [comment]
In the importer, a comment explains that we do not want to refer to the parentPackage of the stub method if the method is not an extension.
If we add the method class and the class package in the model, this may not be true anymore.

**Comment by jecisc** [comment]
I'll propose to add the stub parents to the model. It should not take more memory because those entities are already created and referenced. So adding a link should not change much the memory taken. And this will make things more coherent. 

I found out that FamixDiff gives totally wrong results on stubs in Pharo models because it expect all the entities it manipulates to be in the model. With some entities provided by MooseQuery not in a MooseModel, we have some dead ends in the algos. 

I'll do a PR and leave this PR open if we want to discuss about making the stubs "lighters".

**Comment by jecisc** [comment]
After discussing with Nicolas we think it should be good to have all entities referenced by the model, in the model. So I'll close this issue
