### ISSUE TITLE
Trait TNamedEntity includes too much stuff

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/Famix#59]
TNamedEntity should only be about being named and belonging to a Namespace, it should not force the user to have TSourceEntity, TDependencyQueries, TEntityMetaLevelDependency.
These traits should be added lower in the hierarchy

**Comment by jecisc** [comment]
IMO they should be higher in the hierarchy.

Our hierarchy is currently a mess because it mixes conceptual entities, associations and technical entities.

I think Famix would be much simpler if we splitter those three concept.

Instead of getting everything inheriting from MooseEntity, I would prefer to have MooseAsbtractEntity with 3 subclasses:
- MooseEntity
- MooseAssociation
- MooseTechnicalEntity (or maybe technical entities could just inherit from AbstractEntity)


Thus, everything common for associations and Entities could be on those classes instead of having to put it on all the classes. This means that MooseQuery would not be a generator anymore (which make no sense IMO) and the common API of all entities would be on MooseEntity instead of been split in 80% of the real classes.

**Comment by anneetien** [comment]
Can you give an instance of MooseTechnicalEntity?

It makes sense for me, but before saying go, can you please list what you would like to put directly in each of the three kinds of entities?

**Comment by NicolasAnquetil** [comment]
I agree with the classification Association and Technical
I would add
- Property, for traits only adding a property like FamixTNamed
- Final or Core or something else, for entities that appear in programs (Class, Methodes, Variables, ...)

But I don't see why they should all inherit from a MooseAbstractEntity (well may be the last category could), they are traits and that's it

**Comment by anneetien** [comment]
Now TNamedEntity has only name.
