### ISSUE TITLE
MooseGroup `allTypes` does not return any `FamixTParametricEntity`

### ISSUE THREAD

**Issue by Gabriel-Darbord** [moosetechnology/Famix#712]
Before parametrics, querying a model for all types or classes would also return parameterizable classes and parameterized types.
Now, parametric entities are completely excluded from the result of methods like `allTypes` and `allClasses`.

**Comment by Gabriel-Darbord** [comment]
Reverting #689 seems to fix it, but it conflicts with #690 which isn't breaking anything.

**Comment by Gabriel-Darbord** [comment]
Benchmarking `MooseAbstractGroup >> rawAllUsing:`, I get the following results on a model with roughly 1M entities, including 10K types, with the follwing code:
```st
[ model flush; allTypes ] bench.
```

I kept the current implementation of `allUsing:ofGroupClass:` and only changed `rawAllUsing:` each time.

| description | executions/second |
| --- | ---: |
| [original](https://github.com/moosetechnology/Famix/blob/ed04dbebc90abaae329517ce79c8e0d89b314c96/src/Moose-Core/MooseAbstractGroup.class.st#L108-L115) | 125 |
| [speedup](https://github.com/moosetechnology/Famix/blob/2ee727259aa45dd111ae62827f9b8add151e02a9/src/Moose-Core/MooseAbstractGroup.class.st#L108-L115) | 1.5 |
| stream | 190 |

I'm not sure why the 'speedup' is so slow, it seems that `includesTrait:` is pretty slow, in Pharo 11 at least.
Using the TimeProfiler, I find that 5/6th of the time is spent in that method, so inside `rawAllUsing:`.
For the other implementations, more than 90% of the time is spent on making a MooseGroup out of the result of `rawAllUsing:`.

The streaming implementation is not pretty but it's efficient:
```st
rawAllUsing: aTrait
	"This is an optimization of #allUsing: when we do not need to manipulate a MooseGroup as result."

	| seen |
	aTrait isTrait ifFalse: [ MooseAllUsingOnClass signal ].
	seen := IdentitySet new.
	^ Array streamContents: [ :stream |
		  aTrait allUsers flattened do: [ :directUser |
			  directUser withAllSubclasses do: [ :user |
				  (seen includes: user) ifFalse: [
					  seen add: user.
					  stream nextPutAll: (self entityStorage selectAllWithType: user) ] ] ] ]
```

**Comment by jecisc** [comment]
Thanks for checking this.

I found that depending on the size of the group the speed can vary a lot and I was planning to soon take a look at it to propose an optimized version.

The problem is that queries are using this method also and they often apply it on small moose group and the original implementation is terribly slow on small moose groups.

I was thinking to have one implementation or the other depending on the size of the Moose group. I just did not did it yet because I need to bench with different size of groups to know what is the best

**Comment by Gabriel-Darbord** [comment]
I'll let you cook for speed optimization, but the behavior of `allUsing:` regressed with the last change, and that is my main point of concern.

**Comment by NicolasAnquetil** [comment]
> Thanks for checking this.
> 
> I found that depending on the size of the group the speed can vary a lot and I was planning to soon take a look at it to propose an optimized version.
> 
> The problem is that queries are using this method also and they often apply it on small moose group and the original implementation is terribly slow on small moose groups.
> 
> I was thinking to have one implementation or the other depending on the size of the Moose group. I just did not did it yet because I need to bench with different size of groups to know what is the best

Be careful with clever optimizations to keep the code simple

We do have code efficiency issues, but we are also a very small team.
Code should always be:
- simple to understand and adapt
- generic so that we don't need to adapt

Testing the size of a collection for specific optimization both make the code a little bit more complex and a little bit less generic (there are 2 different paths which potentially mean double work next time we want to change something).

So remember to not overdo the optimization
